version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: root
  AfterInstall:
    - location: scripts/build_image.sh
      timeout: 400
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: root
