name: Build and Deployment

on:
  #push:
    #branches:
     # - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Build application
      run: |
        mvn -B clean package -DskipTests --file pom.xml
    - name: Upload Jar
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/Jar-CICD-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: artifact

      #Deploy the artifact into Ubuntu
      - name: Spring boot code Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          REMOTE_HOST: ${{ secrets.SSH_HOST_DEV }}
          REMOTE_USER: ${{ secrets.USERNAME_DEV }}

      #Post deployment
      - name: Post Deploy
        uses: appleboy/ssh-action@maste
        with:
            host: ${{ secrets.SSH_HOST_DEV }}
            username: ${{ secrets.USERNAME_DEV }}
            key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
            port: 22
            script: |
              sudo systemctl restart jar-cicd
