name: Docker Build and Push
on:
   workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:          
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up JDK 8
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
            java-version: '8'
      - name: Build application
        run: |
            mvn -B clean package -DskipTests --file pom.xml
      - uses: mr-smithers-excellent/docker-build-push@0e68818ea37ba7728f417f03a58e06e68d9d2592 # v5.9
        with:
            image: imajeetyadav/jar-cicd
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          
